// SoonSpot - Bedford NH seed data
// Real developments sourced from Bedford Planning Board records,
// building permits (PermitLink parcel data), and public filings.
// Later this will be replaced by live Supabase data.

export const SPOTS = [
  {
    id: '1',
    name: 'Dogtor House Veterinary Clinic',
    address: '250 South River Road',
    neighborhood: 'South River Corridor',
    distance: '1.2 mi',
    status: 'confirmed',
    category: 'Veterinary / Pet Care',
    description: 'A new 9,000 sq. ft. veterinary clinic is coming to 250 South River Road. Dogtor House LLC received Planning Board approval in January 2025 for the full build-out on this Performance Zone lot.',
    openingDate: '2025–2026',
    source: 'Bedford Planning Board Meeting Jan 27, 2025 · Parcel 23-98-4',
    tags: ['Veterinary', 'Pet Care', 'New Construction'],
    emoji: '🐾',
    color: '#2E86AB',
    verified: true,
    hype: 78,
    confidence: 95,
    latitude: 42.9445,
    longitude: -71.5134,
    updates: [
      { text: 'Planning Board approval granted', date: 'Jan 27, 2025' },
      { text: 'Site plan submitted for 9,000 sq. ft. clinic', date: 'Jan 2025' },
      { text: 'Permit filed — Parcel 23-98-4', date: 'Late 2024' },
    ],
    featured: true,
  },
  {
    id: '2',
    name: 'Evviva Trattoria',
    address: '5 Colby Court (Bedford Grove Plaza)',
    neighborhood: 'South River Corridor',
    distance: '0.9 mi',
    status: 'confirmed',
    category: 'Restaurant',
    description: 'A new Italian restaurant is under construction inside Bedford Grove plaza, next to Boston Interiors. Evviva Trattoria received a sign waiver approval from the Planning Board in January 2025.',
    openingDate: '2025',
    source: 'Bedford Planning Board Jan 27, 2025 · Union Leader Aug 2024',
    tags: ['Italian', 'Restaurant', 'Plaza', 'New Build-Out'],
    emoji: '🍝',
    color: '#C0392B',
    verified: true,
    hype: 88,
    confidence: 97,
    latitude: 42.9398,
    longitude: -71.5201,
    updates: [
      { text: 'Sign waiver approved by Planning Board', date: 'Jan 27, 2025' },
      { text: 'Construction underway at Bedford Grove', date: 'Aug 2024' },
    ],
    featured: true,
  },
  {
    id: '3',
    name: 'New Automotive Dealership',
    address: '213 South River Road',
    neighborhood: 'South River Corridor',
    distance: '1.0 mi',
    status: 'confirmed',
    category: 'Auto Dealership',
    description: 'A brand new automotive dealership is approved and under development at 213 South River Road, featuring 128 parking spaces, landscaping, and a full site build-out on this Performance Zone lot.',
    openingDate: '2025',
    source: 'Bedford Planning Board approval Oct 7, 2024 · Parcel 23-28-22',
    tags: ['Auto', 'Dealership', 'New Construction'],
    emoji: '🚗',
    color: '#1A5276',
    verified: true,
    hype: 65,
    confidence: 98,
    latitude: 42.9412,
    longitude: -71.5178,
    updates: [
      { text: 'Sign package approval granted', date: 'Oct 2025' },
      { text: 'Full project approval granted', date: 'Oct 7, 2024' },
      { text: 'Wetlands variance approved', date: 'Jun 18, 2024' },
    ],
    featured: false,
  },
  {
    id: '4',
    name: 'Chase Bank',
    address: '67-69 South River Road',
    neighborhood: 'South River Corridor',
    distance: '0.6 mi',
    status: 'confirmed',
    category: 'Bank',
    description: 'A newly constructed 3,346 sq. ft. Chase Bank prototype branch on Bedford\'s prime retail corridor, surrounded by Whole Foods, Lowe\'s, Target, Trader Joe\'s, and Hannaford.',
    openingDate: 'Q4 2024',
    source: 'Revere CRE listing · 15-year ground lease filed',
    tags: ['Bank', 'National Chain', 'New Construction'],
    emoji: '🏦',
    color: '#003087',
    verified: true,
    hype: 60,
    confidence: 99,
    latitude: 42.9358,
    longitude: -71.5242,
    updates: [
      { text: 'Branch open / construction complete', date: 'Q4 2024' },
      { text: '15-year ground lease commenced', date: 'Q4 2024' },
      { text: 'Construction started', date: 'Early 2024' },
    ],
    featured: false,
  },
  {
    id: '5',
    name: 'Gas Station & Convenience Store',
    address: 'South River Road (near Land Rover)',
    neighborhood: 'South River Corridor',
    distance: '1.4 mi',
    status: 'rumored',
    category: 'Gas Station / Convenience',
    description: 'South River Road Ventures LLC has proposed a gas station, convenience store, AND car wash on South River Road near the Land Rover dealership. Conceptual discussion at Planning Board — still in early stages.',
    openingDate: 'Unknown',
    source: 'Bedford Planning Board conceptual review · Farley CRE Sep 2025',
    tags: ['Gas Station', 'Convenience', 'Car Wash', 'Proposed'],
    emoji: '⛽',
    color: '#D68910',
    verified: false,
    hype: 52,
    confidence: 55,
    latitude: 42.9481,
    longitude: -71.5098,
    updates: [
      { text: 'Carwash addition proposed at Planning Board', date: 'Sep 2025' },
      { text: 'Conceptual site plan submitted', date: '2025' },
    ],
    featured: false,
  },
  {
    id: '6',
    name: 'Poppy\'s Place Veterinary Clinic',
    address: '13 South River Road',
    neighborhood: 'South River Corridor',
    distance: '0.5 mi',
    status: 'confirmed',
    category: 'Veterinary / Pet Care',
    description: 'Poppy\'s Place LLC is converting 1,261 sq. ft. of former salon space into a veterinary clinic inside an existing building at 13 South River Road.',
    openingDate: '2025',
    source: 'Bedford Planning Board May 5, 2025',
    tags: ['Veterinary', 'Pet Care', 'Renovation'],
    emoji: '🐶',
    color: '#27AE60',
    verified: true,
    hype: 70,
    confidence: 93,
    latitude: 42.9341,
    longitude: -71.5259,
    updates: [
      { text: 'Site plan amendment approved', date: 'May 2025' },
      { text: 'Use change from salon to vet clinic filed', date: 'Apr 2025' },
    ],
    featured: false,
  },
];

export const ALERTS = [
  { id: '1', text: 'New Vet Clinic Approved!',       sub: '1.2 mi away · 250 S River Rd', time: '2 hours ago',  emoji: '🐾', spotId: '1' },
  { id: '2', text: 'Evviva Trattoria — Opening Soon', sub: '0.9 mi away · Bedford Grove',  time: '1 day ago',   emoji: '🍝', spotId: '2' },
  { id: '3', text: 'New Auto Dealership Breaking Ground', sub: '1.0 mi away · 213 S River Rd', time: '3 days ago', emoji: '🚗', spotId: '3' },
  { id: '4', text: 'Gas Station + Car Wash Proposed', sub: '1.4 mi away · S River Rd',     time: '1 week ago',  emoji: '⛽', spotId: '5' },
];